server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/sqli_demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username="cho tai khoan vao day"
spring.datasource.password="Cho mk vao day"

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.thymeleaf.cache=false
